language: node_js

services:
  - docker

sudo: required

node_js:
  - 12.16.1

cache: yarn

script:
  - yarn install
  - yarn build
  - docker build -t inseefr/pearl-jam .

before_script:
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.17.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/

deploy:
  - skip_cleanup: true
    provider: script
    script:
      echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      && docker push inseefr/pearl-jam
    on:
      branch: master

  - skip_cleanup: true
    provider: script
    script:
      kubectl --token $K8S_TOKEN --server $K8S_SERVER --insecure-skip-tls-verify rollout restart deployment/pearl-jam -n queen
    on:
      branch: master
