x-react-volumes: &react-volumes
  - ./:/opt/app
  - /mnt/wslg/.X11-unix:/tmp/.X11-unix
  - /opt/app/node_modules

services:
  playwright-captation:
    image: mcr.microsoft.com/playwright:v1.51.1-noble
    profiles: [captation]
    depends_on:
      - pearl-api
      - questionnaire-api
      - keycloak
    container_name: playwright-captation
    hostname: front
    volumes: *react-volumes
    tty: true
    stdin_open: true # without this node doesn't start
    working_dir: /opt/app
    ipc: host
    network_mode: host
    environment:
      WATCHPACK_POLLING: true
      FAST_REFRESH: true
      DISPLAY: unix:0
      XDG_RUNTIME_DIR: /mnt/wslg/runtime-dir
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      NO_PROXY: ${NO_PROXY}
    command:
      - /bin/bash
      - -c
      - |
        yarn install --network-timeout 100000
        npx playwright codegen http://localhost:3000/
