x-react-volumes: &react-volumes
  - ./:/opt/app

services:
  front:
    container_name: reactapp
    build:
      dockerfile: ./playwright-dev.Dockerfile
    hostname: front
    volumes: *react-volumes
    tty: true
    stdin_open: true # without this node doesn't start
    working_dir: /opt/app
    ipc: host
    ports:
      - 5173:5173
      - 8888:8888
    environment:
      WATCHPACK_POLLING: true
      FAST_REFRESH: true
