apiVersion: apps/v1
kind: Deployment
metadata:
  name: pearl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pearl
  template:
    metadata:
      labels:
        app: pearl
    spec:
      containers:
        - name: pearl
          image: inseefr/pearl-jam:latest
          env:
           - name: QUEEN_URL
             value: 'https://queen.demo.dev.sspcloud.fr'
          env:
           - name: PEARL_API_URL
             value: 'https://pearl-bo.demo.dev.sspcloud.fr'
