name: Playwright Tests
on:
  pull_request:
    branches:
      - '*'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      - PW_EXPERIMENTAL_SERVICE_WORKER_NETWORK_EVENTS: 1
    steps:
      - name: Checkout Pearl
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Run Docker Compose
        run: |
          docker compose --env-file ./.env.docker --profile playwright up -d
          yarn
          npx playwright install --with-deps chromium
          npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
