name: Playwright Tests
on:
  pull_request:
    branches:
      - '*'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Pearl
        uses: actions/checkout@v4
        uses: actions/setup-node@v4
        uses: gacts/install-podman@v1
        with:
          node-version: lts/*
      - name: Run Docker Compose
        run: |
          cat ./.env.docker
          podman machine start
          podman compose --env-file ./.env.docker up -d
          yarn
          npx playwright install --with-deps chromium
          lsof -i -P -n | grep LISTEN
          podman ps
          sudo netstat -tulpn
          npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
