name: Playwright Tests
on:
  pull_request:
    branches:
      - '*'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Pearl
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Run Docker Compose
        run: |
          docker compose --env-file ./.env.docker up -d
      - name: Wait for Queen
        uses: cygnetdigital/wait_for_response@v2.0.0
        with:
          url: 'https://localhost:5001/assets/remoteEntry.js'
          responseCode: '200'
      - name: Run Playwright tests
        run: |
          yarn
          npx playwright install --with-deps chromium
          npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
