name: Playwright Tests
on:
  pull_request:
    branches:
      - '*'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Pearl
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Run Docker Compose
        run: |
          docker compose --env-file ./.env.docker up -d
          yarn
          npx playwright install --with-deps chromium
          docker ps
      - name: Wait for localhost:3000
        run: |
          while ! nc -z localhost 3000; do
            echo "Waiting for port 3000..."
            sleep 1
          done
      - timeout-minutes: 5
      - name: Wait for remoteEntry.js
        run: |
          until curl --output /dev/null --silent --head --fail http://localhost:5001/assets/remoteEntry.js; do
            echo "Waiting for remoteEntry.js..."
            sleep 1
          done
      - timeout-minutes: 5
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
