name: Playwright Tests
on:
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Pearl
        uses: actions/checkout@v4
        with:
          path: Pearl-Jam
      - name: Checkout Queen
        uses: actions/checkout@v4
        with:
          repository: inseefr/drama-queen
          path: Drama-Queen
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Clone Queen
        run: |
          ls
